### ISSUE TITLE
All jobs return the same label ID on event listener

### ISSUE THREAD

**Issue by xelons** [samderlust/async_queue#8]
Create an async queue
addQueueListener and print the event
Add job1 with label ID 1
queue listener prints event of added job1 with label as ID 1 as expected.
Add job2 with label ID 2
queue listener prints event of added job2 with label as ID 1 - Wrong
Add job3 with label ID 3
queue listener prints event of added job3 with label as ID 1 - Wrong

No matter how many jobs are added to the queue, they all show on the event as label ID from the first job added.

**Comment by samderlust** [comment]
@xelons  I'm looking into it

**Comment by samderlust** [comment]
@xelons  issue is fixed on 2.0.1

**Comment by xelons** [comment]
Unfortunately the problem is still there when adding a new job. The event that is sent when new job is added always has the ID of the first element, regardless if the new jobs have different ids or not.

This is the code responsible of the issue:

>   /// to add node into queue
  void _enqueue(AsyncNode node) {
    if (_first == null) {
      _first = node;
      _last = node;
    } else {
      _last!.next = node;
      _last = node;
    }
    _size++;
    _emitEvent(QueueEventType.newJobAdded, _first!.label);
  }

_first is not null, and the newJobAdded event will always send the label of the first job and not the new ones. Changing _first!.label to node.label should probably solve it.

**Comment by samderlust** [comment]
@xelons THanks for your feedback. I think I accidentally hit revert the change on that.
I just released 2.0.2 with the fix for that
